// SNMPWRAPPER-TEST-MIB implemented with the code generated by snmpwrap-mibgen (snmpwrap_add_mib in CMake).
// Same behaviour and command line as examples/test_agent.cpp, so the same integration suite runs against it:
//
//   generated_test_agent [--socket <agentx>] [--trap-every <s>] [--big-table <rows>]
//
// No OIDs, types, ranges or index layouts appear here – they are all in the generated
// snmpwrapper_test_mib.hpp, which the compiler checks this class against.

#include <chrono>
#include <csignal>
#include <cstdlib>
#include <iostream>
#include <map>
#include <string>

#include "snmpwrapper_test_mib.hpp"

using namespace snmpwrapper_test_mib;
using snmpwrap::RowStatus;

namespace {

snmpwrap::Agent* g_agent = nullptr;
void onSignal(int) {
    if (g_agent) g_agent->stop();
}

class TestMib : public Instrumentation {
public:
    explicit TestMib(std::uint32_t bigRows) : bigRows_(bigRows) {
        conns_[{{10, 0, 0, 1}, 80, "web"}] = SwtConnState::established;
        conns_[{{10, 0, 0, 1}, 443, "tls"}] = SwtConnState::listen;
        conns_[{{10, 0, 0, 2}, 22, "ssh"}] = SwtConnState::established;
    }

    std::string name = "snmpwrap";
    std::int32_t limit = 50;

    // --- scalars ---------------------------------------------------------------------------
    std::string swtName() override { return name; }
    void setSwtName(const std::string& v) override { name = v; }
    std::uint32_t swtCounter() override { return ++counter_; }
    std::uint32_t swtGauge() override { return seconds() % 100; }
    std::int32_t swtLimit() override { return limit; }
    void setSwtLimit(std::int32_t v) override { limit = v; }
    std::uint32_t swtUptime() override { return seconds() * 100; }
    std::uint64_t swtBigCounter() override { return 4294967297ULL; }

    // --- swtTable ----------------------------------------------------------------------------
    std::vector<SwtEntryIndex> swtTableRows() override {
        std::vector<SwtEntryIndex> out;
        for (const auto& [i, r] : rows_) out.push_back({i});
        return out;
    }
    std::string swtEntryName(const SwtEntryIndex& i) override { return rows_.at(i.swtIndex).name; }
    void setSwtEntryName(const SwtEntryIndex& i, const std::string& v) override {
        if (v == "commitfail") throw snmpwrap::SetError(snmpwrap::ErrorStatus::CommitFailed, "injected failure");
        rows_.at(i.swtIndex).name = v;
    }
    std::uint32_t swtEntryValue(const SwtEntryIndex& i) override { return rows_.at(i.swtIndex).value; }
    void setSwtEntryValue(const SwtEntryIndex& i, std::uint32_t v) override { rows_.at(i.swtIndex).value = v; }
    SwtEntryStatus swtEntryStatus(const SwtEntryIndex& i) override { return rows_.at(i.swtIndex).status; }
    void setSwtEntryStatus(const SwtEntryIndex& i, SwtEntryStatus v) override { rows_.at(i.swtIndex).status = v; }

    // --- swtRowTable (RowStatus) ----------------------------------------------------------------
    std::vector<SwtRowEntryIndex> swtRowTableRows() override {
        std::vector<SwtRowEntryIndex> out;
        for (const auto& [i, r] : rowTable_) out.push_back({i});
        return out;
    }
    std::string swtRowName(const SwtRowEntryIndex& i) override { return rowTable_.at(i.swtRowIndex).name; }
    void setSwtRowName(const SwtRowEntryIndex& i, const std::string& v) override {
        if (v == "commitfail") throw snmpwrap::SetError(snmpwrap::ErrorStatus::CommitFailed, "injected failure");
        rowTable_.at(i.swtRowIndex).name = v;
    }
    std::uint32_t swtRowValue(const SwtRowEntryIndex& i) override { return rowTable_.at(i.swtRowIndex).value; }
    void setSwtRowValue(const SwtRowEntryIndex& i, std::uint32_t v) override { rowTable_.at(i.swtRowIndex).value = v; }
    void createSwtRowEntry(const SwtRowEntryIndex& i, const SwtRowEntryValues& v) override {
        RowEntry e;
        e.name = v.swtRowName.value_or("");
        e.value = v.swtRowValue.value_or(0);  // the generated code pre-fills the DEFVAL (0)
        rowTable_[i.swtRowIndex] = e;
    }
    void destroySwtRowEntry(const SwtRowEntryIndex& i) override { rowTable_.erase(i.swtRowIndex); }
    RowStatus swtRowStatus(const SwtRowEntryIndex& i) override { return rowTable_.at(i.swtRowIndex).status; }
    void setSwtRowStatus(const SwtRowEntryIndex& i, RowStatus s) override { rowTable_.at(i.swtRowIndex).status = s; }
    bool swtRowEntryComplete(const SwtRowEntryIndex& i) override { return !rowTable_.at(i.swtRowIndex).name.empty(); }

    // --- swtConnTable (composite index) ---------------------------------------------------------
    std::vector<SwtConnEntryIndex> swtConnTableRows() override {
        std::vector<SwtConnEntryIndex> out;
        for (const auto& [i, s] : conns_) out.push_back(i);
        return out;
    }
    SwtConnState swtConnState(const SwtConnEntryIndex& i) override { return conns_.at(i); }
    void setSwtConnState(const SwtConnEntryIndex& i, SwtConnState v) override { conns_.at(i) = v; }

    // --- swtBigTable: big table, Next/Has overridden so the rows are never enumerated --------------
    std::vector<SwtBigEntryIndex> swtBigTableRows() override { return {}; }
    std::optional<SwtBigEntryIndex> swtBigTableNext(const snmpwrap::Oid* after) override {
        std::uint64_t next = 2;
        if (after && !after->empty()) next = (static_cast<std::uint64_t>((*after)[0]) / 2 + 1) * 2;
        if (next / 2 > bigRows_) return std::nullopt;
        return SwtBigEntryIndex{static_cast<std::uint32_t>(next)};
    }
    bool swtBigTableHas(const SwtBigEntryIndex& i) override {
        return i.swtBigIndex >= 2 && i.swtBigIndex % 2 == 0 && i.swtBigIndex / 2 <= bigRows_;
    }
    std::uint32_t swtBigValue(const SwtBigEntryIndex& i) override { return i.swtBigIndex / 2; }
    std::uint32_t swtBigDouble(const SwtBigEntryIndex& i) override { return i.swtBigIndex; }

private:
    struct Row {
        std::string name;
        std::uint32_t value;
        SwtEntryStatus status;
    };
    struct RowEntry {
        std::string name;
        std::uint32_t value = 0;
        RowStatus status = RowStatus::NotReady;
    };

    std::uint32_t seconds() const {
        return static_cast<std::uint32_t>(
            std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now() - start_).count());
    }

    std::uint32_t bigRows_;
    std::uint32_t counter_ = 0;
    std::map<std::int32_t, Row> rows_{{1, {"eth0", 100, SwtEntryStatus::up}},
                                      {2, {"eth1", 200, SwtEntryStatus::down}},
                                      {3, {"lo", 5, SwtEntryStatus::testing}}};
    std::map<std::int32_t, RowEntry> rowTable_;
    std::map<SwtConnEntryIndex, SwtConnState> conns_;
    std::chrono::steady_clock::time_point start_ = std::chrono::steady_clock::now();
};

}  // namespace

int main(int argc, char** argv) {
    snmpwrap::AgentConfig config;
    config.name = "snmpwrap-generated-test-agent";
    int trapEvery = 0;
    std::uint32_t bigRows = 0;
    for (int i = 1; i < argc; ++i) {
        const std::string a = argv[i];
        if (a == "--socket" && i + 1 < argc) config.agentxSocket = argv[++i];
        else if (a == "--trap-every" && i + 1 < argc) trapEvery = std::atoi(argv[++i]);
        else if (a == "--big-table" && i + 1 < argc) bigRows = static_cast<std::uint32_t>(std::atol(argv[++i]));
        else {
            std::cerr << "usage: " << argv[0] << " [--socket s] [--trap-every s] [--big-table n]\n";
            return 2;
        }
    }

    try {
        snmpwrap::Agent agent(config);
        g_agent = &agent;
        std::signal(SIGINT, onSignal);
        std::signal(SIGTERM, onSignal);

        TestMib impl(bigRows);
        registerMib(agent, impl);  // generated: registers every object of SNMPWRAPPER-TEST-MIB

        std::cerr << "generated test agent connecting to " << config.agentxSocket << "\n";
        agent.start();
        auto nextTrap = std::chrono::steady_clock::now() + std::chrono::seconds(trapEvery);
        while (agent.poll()) {
            if (trapEvery > 0 && std::chrono::steady_clock::now() >= nextTrap) {
                sendSwtAlarm(agent, impl.name, impl.limit);  // generated, typed
                nextTrap += std::chrono::seconds(trapEvery);
            }
        }
    } catch (const std::exception& e) {
        std::cerr << "error: " << e.what() << "\n";
        return 1;
    }
    return 0;
}
